apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserver1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microserver1
  template:
    metadata:
      labels:
        app: microserver1
    spec:
      containers:
      - name: microserver1
        image: neehargadam/microservice1:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000